### ISSUE TITLE
Add background images.

### ISSUE THREAD

**Issue by lmagnuson07** [lmagnuson07/2d-side-scroller#10]
# TO-DO's
- [x] Create a base Layer class
- [x] Create a background class
- [x] Add a ground margin property to the game class
- [x] Optimize the speed modifier values of each layer
- [x] Control the speed of background images with deltaTime in Layer update method
- [x] Draw the image on canvas
  - [x] Draw the second, offset image on canvas to the right of first image
  - [x] Draw a third image (background images aren't very wide)
- [x] Randomise the Y value of the beetle enemy

**Comment by lmagnuson07** [comment]
Background images added and optimized. Separated the lava from the ground layer in photoshop. Fullscreen bug is now resolved.
