### ISSUE TITLE
Add the UI for score, lives, and other messages

### ISSUE THREAD

**Issue by lmagnuson07** [lmagnuson07/2d-side-scroller#11]
# TO-DO's
- [x] Add the UI class
- [x] Add a draw method
  - [x] Wrap the whole draw method in save() and restore() methods
- [x] Set the font (pick one from google fonts)
- [x] Pick an image for the "lives" and display it with a for loop 
- [x] Add a message for winning and losing conditions
- [x] Player loses lives when a collision is detected 
  - [x] Set winning condition to surviving for a certain amount of time, with setTimeout() for now
  - [x] Display message for winning condition
  - [x] Display losing message when player runs out of live

**Comment by lmagnuson07** [comment]
All UI elements added. May add more later. Found a font that I'm really happy with on google fonts.
