### ISSUE TITLE
Add floating messages

### ISSUE THREAD

**Issue by lmagnuson07** [lmagnuson07/2d-side-scroller#12]
# TO-DO's 
- [x] Add a floating messages class 
- [x] Add a floatingMessages array to the game class
- [x] In the checkCollision() on the player class, push a new FloatingMessage to the floatingMessages array for each collision
- [x] Loop through floatingMessages array in the update method on game class, calling FloatingMessages update method
- [x] Filter the array for messages markedForDeletion set to false
- [x] Set markedForDeletion to true in the update method on FloatingMessages class, based on an incremental timer
  - [x] Wrap the logic in this update method in a deltaTime check.

**Comment by lmagnuson07** [comment]
Floating messages added to show the points depending on the current state.
