### ISSUE TITLE
Add collision animation and simple player animation for attacks (roll and dive for now)

### ISSUE THREAD

**Issue by lmagnuson07** [lmagnuson07/2d-side-scroller#13]
# TO-DO's 
- [x] Add a collisionAnimation class 
- [x] Add a draw and update method
- [x] Select a collisions image for the animation
- [x] Add a collisions array to the game class
  - [x] Push to the array a new CollisionAnimation in the checkCollision() method on player class
- [x] Loop through the collisions array in the game update method and call the collision update methods
- [x] Filter the collisions with markedForDeletion set to false
- [x]  Mark the collision for deletion when it completes its animation in the CollisionAnimation update method
- [x] Add roll state for the player that will increase game speed
  - [x] Add the animation for the roll state
  - [x] Add the keybind for the roll state
- [x] Add a sliding state for the player that will increase game speed
  - [x] Add the animation for the sliding state
  - [x] Add the keybind for the sliding state
- [x] Add a dive state class that will be entered when in the air
  - [x] Add the same animation as roll state  
  - [x] Add the keybind for the dive sate

**Comment by lmagnuson07** [comment]
Collision animation (dust cloud) successfully implemented. Can't figure out how to rotate the animation. Will add to a bug issue.
