### ISSUE TITLE
Finalize basic spritesheet animation for hit animations.

### ISSUE THREAD

**Issue by lmagnuson07** [lmagnuson07/2d-side-scroller#14]
# TO-DO's 
- [x] Update the player and player mirrored spritesheets, removing the block animation and replacing it with the hit and dizzy animations
- [x] Add a state for getting hit (hit animation) when above half lives
  - [x] Lock the player in the animation until the animation finishes
- [x] Add a state for getting hit (dizzy animation) when below half lives
  - [x]  Lock the player in the animation until the animation finishes (dizzy should be the longer animation)

**Comment by lmagnuson07** [comment]
Locks the player in a hit state at first, than when they are under 50% lives, locks them in a dizzy state. Player is locked in the state until the animation is over (plays once).
