### ISSUE TITLE
Implement enemy variety

### ISSUE THREAD

**Issue by lmagnuson07** [lmagnuson07/2d-side-scroller#15]
# TO-DO's 
- [x] Implement randomness to the enemy size
  - [x] Add a sizemodifier to each enemy class and use it in the draw method
- [x] Add a spirit flying enemy
  - [x] Use sin to give it a vertical arc
- [x] Add a spider enemy and give it a web as it drops down from the top of canvas
  - [x] Make spider walk to the left side of canvas after it reaches the ground 
  - [x] Make the web fall/detract from the ceiling and disappear

**Comment by lmagnuson07** [comment]
Two new enemies added. Sufficient for the first level.
