### ISSUE TITLE
Add an energy bar

### ISSUE THREAD

**Issue by lmagnuson07** [lmagnuson07/2d-side-scroller#16]
# TO-DO's
- [x] Add an EnergyBar class and make a property on the Game class
- [x] Add maxEnergy and energy properties on the Game class so they can be accessed anywhere
- [x] Draw a full energy bar on canvas, under the live's hearts
- [x] Add a deltatime check to the Update method of the EnergyBar class
- [x] Add the logic to the Update method
- [x] Call the update method in every state, passing it deltaTime from the state classes. Set the energy increment/decrement for each state
- [x] Ensure the energy bar is decreasing/increasing depending on which state it is in and staying within the bounds of its border
- [x] Add an empty energy flag to the EnergyBar class to record when energy has reached 0
- [x] Cancel the rolling, sliding, and diving states if energy reaches 0 (based on the empty energy flag)
- [x] Add a check in the update class that checks when energy is 0, then turns the flag to true
- [x] Using the energy flag, lock players out of attack animations until energy is full (energy flag is false)

**Comment by lmagnuson07** [comment]
Energy fully implemented.
