### ISSUE TITLE
Finish up basic features 

### ISSUE THREAD

**Issue by lmagnuson07** [lmagnuson07/2d-side-scroller#17]
# TO-DO's 
- [ ] Adjust the size and position of the player hitbox in rolling animation 
- [ ] Add functionality to the dodge class
  - [ ] When player is in dodge state, enemies will walk by and no collision will take place
