### ISSUE TITLE
Initial setup 

### ISSUE THREAD

**Issue by lmagnuson07** [lmagnuson07/2d-side-scroller#2]
# TO-DOs
- [x] setup the responsive elements
- [x] implement a full-screen button
- [x] add loading message (hide when loaded)
- [x] wrap the main.js code in a window event listener
- [x] implement the animation loop
- [x] implement the game class
- [x] implement the player class
- [x] implement the input class 
- [x] create the delta time variable
- [x] Draw a square on the screen to represent the player

**Comment by lmagnuson07** [comment]
Animated the square as well with a simple increment for now.
