### ISSUE TITLE
Sprite animation and collision detection

### ISSUE THREAD

**Issue by lmagnuson07** [lmagnuson07/2d-side-scroller#3]
# TO-DO's 
- [x] Animate the first row of the player sprite sheet
  - [x] Ensure it animates the second row of the animation (has 20ish frames)
- [x] Animate the first row of the player mirrored sprite sheet
  - [x] Ensure it animates the second row of the animation
- [x] Animate a single enemy
  - [x] Ensure it animates the second row if needed (some have 20, others have 30 frames)
- [x] Implement basic circular hitboxes for collision detection 
  - [x] Optimize hitbox size for player
  - [x] Optimize hitbox size for enemy class, so that each enemy type can have their own hitbox dimensions
- [x] Add a game-over variable to game class to test collisions for now
- [x] Add a debug mode, accessed by inputting "f1" to display drawn hitboxes
- [x] Implement a game speed to control the relative position of enemies
- [x] Optimize jumping and falling so that when no horizontal movement is input, set game speed to 0

**Comment by lmagnuson07** [comment]
Basic sprite animation and collision detection are complete. Debug mode and game speed variable implemented.

**Comment by lmagnuson07** [comment]
Basic sprite animation and collision detection are complete. Debug mode and game speed variable implemented.
