### ISSUE TITLE
Implement player states

### ISSUE THREAD

**Issue by lmagnuson07** [lmagnuson07/2d-side-scroller#4]
# TO-DOs
- [x] Create a player states class
- [x] Add an enter method. Call in the setState() on player class.
- [x] Add a handleInput method, call it in the player update method.
- [x] Store states in a enum
- [x] Implement a setState() on player class
- [x] Add an idle state, to index 0 of the states array, and set current state to idles state in game class
- [x] Implement the vertical movement via states (spacebar input)
- [x] Implement a sitting state (s) that changes the height of the square (for now)
- [x] Implement vertical boundaries

**Comment by lmagnuson07** [comment]
Sitting, idle, running, jumping, and falling states implemented. Discovered an issue on my laptop (runs at 30 fps) with the jumping animation. Added a bug issue to address the problem later.
